import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const SITE_URL = "https://nadine.luxor.ly";

const staticPages = [
  { path: "/", priority: "1.0", changefreq: "weekly" },
  { path: "/collections", priority: "0.9", changefreq: "weekly" },
  { path: "/cart", priority: "0.3", changefreq: "monthly" },
  { path: "/faq", priority: "0.5", changefreq: "monthly" },
  { path: "/contact", priority: "0.5", changefreq: "monthly" },
  { path: "/track-order", priority: "0.4", changefreq: "monthly" },
  { path: "/about", priority: "0.6", changefreq: "monthly" },
  { path: "/shipping-policy", priority: "0.3", changefreq: "yearly" },
  { path: "/refund-policy", priority: "0.3", changefreq: "yearly" },
  { path: "/terms", priority: "0.3", changefreq: "yearly" },
  { path: "/privacy", priority: "0.3", changefreq: "yearly" },
  { path: "/wishlist", priority: "0.3", changefreq: "monthly" },
];

// Product IDs — derived from the exported catalog (regenerated by export-products.ts before this script)
const productsJson = JSON.parse(readFileSync(join(root, "public", "products.json"), "utf-8"));
const catalog = Array.isArray(productsJson) ? productsJson : productsJson.products ?? [];
const productIds = catalog.map((p) => p && p.id).filter(Boolean);


const now = new Date().toISOString();

function xml(url) {
  return `  <url>
    <loc>${escapeXml(url.loc)}</loc>
    <lastmod>${url.lastmod || now}</lastmod>
    <changefreq>${url.changefreq || "monthly"}</changefreq>
    <priority>${url.priority || "0.5"}</priority>
  </url>`;
}

function escapeXml(s) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const urls = [
  ...staticPages.map((p) => ({
    loc: `${SITE_URL}${p.path}`,
    priority: p.priority,
    changefreq: p.changefreq,
    lastmod: now,
  })),
  ...productIds.map((id) => ({
    loc: `${SITE_URL}/product/${id}`,
    priority: "0.8",
    changefreq: "monthly",
    lastmod: now,
  })),
];

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(xml).join("\n")}
</urlset>`;

const outPath = join(root, "public", "sitemap.xml");
writeFileSync(outPath, sitemap, "utf-8");
console.log(`✅ Sitemap generated: ${outPath} (${urls.length} URLs)`);
